///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace testForGit
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the testForGitRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("737df573-9528-4b6b-a434-1e7a1bfda53a")]
    public partial class testForGitRepository : RepoGenBaseFolder
    {
        static testForGitRepository instance = new testForGitRepository();

        /// <summary>
        /// Gets the singleton class instance representing the testForGitRepository element repository.
        /// </summary>
        [RepositoryFolder("737df573-9528-4b6b-a434-1e7a1bfda53a")]
        public static testForGitRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public testForGitRepository() 
            : base("testForGitRepository", "/", null, 0, false, "737df573-9528-4b6b-a434-1e7a1bfda53a", ".\\RepositoryImages\\testForGitRepository737df573.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("737df573-9528-4b6b-a434-1e7a1bfda53a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class testForGitRepositoryFolders
    {
    }
#pragma warning restore 0436
}